### ISSUE TITLE
What are 3 Sass mixins/functions you always find yourself using in projects?

### ISSUE THREAD

**Issue by una** [HugoGiraudel/ama#32]
Just 3!

**Comment by HugoGiraudel** [comment]
I'd say none. Over the years, I learnt to reduce the amount of Sass helpers I need close to 0, in order to prevent any complexity overhead, especially in regard to other developers in the team. Mixins and functions are usually very specific to the project, so that I quite never re-use a mixin/function from a project to another.

Although depending on the amount of configuration I am dealing with on the Sass side of the project, and mostly regarding the usage of nested maps, I usually import my deep-get function.

```scss
/// A helper function to extend the `map-get(..)` syntax in order to be able to
/// retrieve data from nested maps.
/// @param {Map} $map - Map
/// @param {Arglist} $keys - Key chain
/// @return {*} - Desired value
@function map-fetch($map, $keys...) {
  @each $key in $keys {
    $map: map-get($map, $key);

    @if type-of($map) == 'null' {
      @return $map;
    }
  }

  @return $map;
}
```

And if I had to name a mixin, I'd probably say the ellipsis one. The ability to restrict a piece of text on a single line, ellipsed if too long, is needed in most if not all projects. Wrapping those 3 odd and unrelated CSS declarations in a mixin is easier than repeating the same comment over and over again. 

```scss
/// Force a piece of text on a single line, ending it with an ellipsis if too long
/// @example scss
///   .foo {
///     @include ellipsis;
///   }
/// @example css
///   .foo {
///     white-space: nowrap;
///     overflow: hidden;
///     text-overflow: ellipsis;
///   }
@mixin ellipsis {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
